const LOW_QUALITY_BLOG_SLUGS = [
  "tennis-intermediate-to-advanced-transition",
  "tennis-mental-focus-recovery",
  "tennis-mental-routine-5steps",
  "tennis-mental-routine-control-guide",
  "tennis-postmatch-recovery-routine",
  "tennis-power-of-routine",
  "tennis-serve-rhythm-science",
  "tennis-serve-timing-and-spin-guide",
  "tennis-shoes-balance-guide",
  "tennis-shoes-selection-guide",
  "tennis-volley-technique-guide",
  "winter-indoor-tennis-training-routine",
  "tennis-strategy-vs-lefty",
  "tennis-drop-shot-mastery",
  "tennis-lob-defense-offense",
  "tennis-overhead-smash-guide",
  "tennis-slice-backhand-mastery",
  "tennis-return-of-serve-strategy",
  "tennis-string-tension-guide",
  "tennis-grip-size-selection",
  "tennis-overgrip-guide",
  "tennis-dampener-effectiveness",
  "tennis-wrist-knee-pain-care",
  "tennis-tiebreak-strategy-guide",
  "tennis-second-serve-confidence-guide",
  "tennis-clay-court-sliding-guide",
  "tennis-hard-court-recovery-guide",
  "tennis-grass-court-movement-guide",
  "tennis-doubles-serve-formation-guide",
  "tennis-return-positioning-by-surface",
  "tennis-matchday-warmup-routine",
  "tennis-cooldown-stretching-routine",
  "tennis-sleep-recovery-guide",
  "tennis-hydration-electrolyte-guide",
  "tennis-hot-weather-match-guide",
  "tennis-cold-weather-match-guide",
  "tennis-practice-journal-guide",
  "tennis-unforced-error-reduction-guide",
  "tennis-approach-shot-guide",
  "tennis-split-step-timing-guide",
  "tennis-serve-plus-one-patterns",
  "tennis-mental-reset-between-points",
  "tennis-junior-training-roadmap",
  "tennis-adult-beginner-first-90-days",
  "tennis-partner-practice-drills",
  "tennis-wall-practice-guide",
  "tennis-doubles-net-player-guide",
  "tennis-kick-serve-guide",
  "tennis-slice-serve-guide",
  "tennis-forehand-depth-control-guide",
  "tennis-backhand-return-guide",
  "tennis-match-video-review-guide",
  "tennis-tournament-preparation-checklist",
  "tennis-grip-pressure-guide",
  "tennis-deuce-court-strategy",
  "tennis-ad-court-strategy",
  "tennis-singles-positioning",
  "tennis-first-serve-percentage",
  "tennis-net-approach-timing",
  "tennis-passing-shot-guide",
  "tennis-high-ball-handling",
  "tennis-low-ball-technique",
  "tennis-inside-out-forehand",
  "tennis-cross-court-rally",
  "tennis-down-the-line-timing",
  "tennis-moon-ball-counter",
  "tennis-serve-and-volley-modern",
  "tennis-chip-and-charge",
  "tennis-two-handed-backhand-power",
  "tennis-one-handed-backhand-guide",
  "tennis-topspin-generation",
  "tennis-flat-shot-when-to-use",
  "tennis-angle-shot-technique",
  "tennis-defensive-lob-mastery",
  "tennis-between-sets-recovery",
  "tennis-pre-match-nutrition",
  "tennis-core-strength-training",
  "tennis-shoulder-mobility",
  "tennis-ankle-stability",
  "tennis-eye-tracking-training",
  "tennis-breathing-technique",
  "tennis-self-talk-strategy",
  "tennis-match-journal-template",
  "tennis-korean-ntrp-mapping-guide",
  "tennis-korea-summer-humidity",
  "tennis-korea-winter-indoor-routine",
  "tennis-korea-spring-fine-dust",
  "tennis-office-worker-evening-routine",
  "tennis-racket-100k-beginner",
  "tennis-ntrp-2-to-3",
  "tennis-ntrp-3-to-3-5",
  "tennis-doubles-partner-finding",
  "tennis-tennis-elbow-early-signs",
  "indoor-court-booking-tips",
  "junior-parent-tennis-guide",
  "senior-tennis-injury-safe-guide",
  "seoul-best-tennis-courts",
  "winter-tennis-training",
  "tennis-mental-techniques",
  "backhand-swing-correction",
  "racket-weight-styles",
  "tennis-grip-replacement",
  "forehand-body-balance",
  "racket-care-mistakes",
  "string-tension-feel-guide",
  "common-tennis-racket-mistakes",
  "alcaraz-vs-sinner-analysis",
  "best-tennis-rackets-2024",
  "tennis-elbow-prevention",
] as const;

const LOW_QUALITY_BLOG_SLUG_SET = new Set<string>(LOW_QUALITY_BLOG_SLUGS);

export function isLowQualityBlogSlug(slug: string) {
  return LOW_QUALITY_BLOG_SLUG_SET.has(slug);
}

export function isIndexableBlogSlug(slug: string) {
  return !isLowQualityBlogSlug(slug);
}

export function getLowQualityBlogSlugs() {
  return [...LOW_QUALITY_BLOG_SLUGS];
}
