const BLOG_BATCH = [
  { slug: "tennis-tiebreak-strategy-guide", title: "타이브레이크 운영 가이드", description: "타이브레이크에서 서두르지 않고 득점 확률을 높이는 전술, 루틴, 리스크 관리 기준을 정리합니다.", category: "Strategy" },
  { slug: "tennis-second-serve-confidence-guide", title: "세컨드 서브 자신감 가이드", description: "더블폴트를 줄이면서도 공격성을 잃지 않는 세컨드 서브 설계법을 설명합니다.", category: "Strategy" },
  { slug: "tennis-clay-court-sliding-guide", title: "클레이코트 슬라이딩 입문", description: "클레이코트에서 미끄러지듯 움직이기 위한 기본 원리와 안전한 훈련 순서를 소개합니다.", category: "Technique" },
  { slug: "tennis-hard-court-recovery-guide", title: "하드코트 경기 후 회복 가이드", description: "하드코트 충격 누적을 줄이기 위한 회복 루틴과 관리 포인트를 정리합니다.", category: "Recovery" },
  { slug: "tennis-grass-court-movement-guide", title: "잔디코트 움직임 가이드", description: "잔디코트 특유의 낮은 바운드와 빠른 리듬에 적응하는 움직임 전략을 설명합니다.", category: "Technique" },
  { slug: "tennis-doubles-serve-formation-guide", title: "복식 서브 포메이션 가이드", description: "복식에서 자주 쓰는 서브 포메이션과 점수 상황별 선택 기준을 실전 중심으로 정리합니다.", category: "Doubles" },
  { slug: "tennis-return-positioning-by-surface", title: "코트별 리턴 포지션 가이드", description: "하드, 클레이, 잔디에서 리턴 위치를 어떻게 다르게 잡아야 하는지 설명합니다.", category: "Strategy" },
  { slug: "tennis-matchday-warmup-routine", title: "경기 당일 워밍업 루틴", description: "경기 전 몸과 집중력을 함께 끌어올리는 워밍업 구성법을 소개합니다.", category: "Training" },
  { slug: "tennis-cooldown-stretching-routine", title: "경기 후 쿨다운 스트레칭 루틴", description: "경기 후 긴장을 풀고 다음 세션 피로를 줄이는 회복 루틴을 정리합니다.", category: "Recovery" },
  { slug: "tennis-sleep-recovery-guide", title: "수면과 테니스 회복 가이드", description: "테니스 경기력과 회복 속도에 영향을 주는 수면 준비와 취침 루틴을 설명합니다.", category: "Recovery" },
  { slug: "tennis-hydration-electrolyte-guide", title: "수분·전해질 관리 가이드", description: "경기 중 집중력 저하와 탈수를 막기 위한 수분 섭취와 전해질 전략을 정리합니다.", category: "Nutrition" },
  { slug: "tennis-hot-weather-match-guide", title: "폭염 경기 대처 가이드", description: "더운 날씨에 체력 손실을 줄이고 경기 운영을 안정적으로 유지하는 방법을 설명합니다.", category: "Conditioning" },
  { slug: "tennis-cold-weather-match-guide", title: "추운 날 경기 운영 가이드", description: "낮은 기온에서도 몸을 보호하고 타이밍을 유지하는 실전 운영법을 소개합니다.", category: "Conditioning" },
  { slug: "tennis-practice-journal-guide", title: "테니스 연습일지 작성 가이드", description: "연습 내용을 기록하고 개선 포인트를 찾는 연습일지 작성법을 정리합니다.", category: "Training" },
  { slug: "tennis-unforced-error-reduction-guide", title: "범실 줄이기 훈련 가이드", description: "불필요한 실수를 줄이기 위한 판단, 루틴, 코스 선택 기준을 설명합니다.", category: "Technique" },
  { slug: "tennis-approach-shot-guide", title: "어프로치 샷 가이드", description: "짧은 볼을 공격 기회로 바꾸는 어프로치 샷 운영법을 실전 중심으로 정리합니다.", category: "Technique" },
  { slug: "tennis-split-step-timing-guide", title: "스플릿스텝 타이밍 가이드", description: "풋워크의 출발점인 스플릿스텝 타이밍을 상황별로 이해하고 연습하는 법을 설명합니다.", category: "Footwork" },
  { slug: "tennis-serve-plus-one-patterns", title: "서브 플러스 원 패턴 가이드", description: "서브 다음 공까지 연결하는 패턴 플레이의 기본 구조를 설명합니다.", category: "Strategy" },
  { slug: "tennis-mental-reset-between-points", title: "포인트 사이 멘탈 리셋 가이드", description: "실수 뒤에 흔들리지 않고 짧은 루틴으로 집중을 회복하는 방법을 소개합니다.", category: "Mental" },
  { slug: "tennis-junior-training-roadmap", title: "주니어 테니스 성장 로드맵", description: "주니어 선수가 단계별로 무엇을 우선 학습해야 하는지 로드맵 형태로 정리합니다.", category: "Training" },
  { slug: "tennis-adult-beginner-first-90-days", title: "성인 입문자 첫 90일 가이드", description: "성인 초보가 첫 3개월 동안 안정적으로 기본기를 쌓는 학습 순서를 제안합니다.", category: "Beginner" },
  { slug: "tennis-partner-practice-drills", title: "파트너 연습 드릴 가이드", description: "코치 없이도 둘이서 효율적으로 진행할 수 있는 파트너 드릴을 정리합니다.", category: "Training" },
  { slug: "tennis-wall-practice-guide", title: "벽치기 훈련 가이드", description: "혼자서도 반복 훈련 효과를 낼 수 있는 벽치기 루틴과 목표 설정법을 설명합니다.", category: "Training" },
  { slug: "tennis-doubles-net-player-guide", title: "복식 네트 플레이어 가이드", description: "복식에서 네트 플레이어가 위치, 리액션, 마무리를 어떻게 가져가야 하는지 설명합니다.", category: "Doubles" },
  { slug: "tennis-kick-serve-guide", title: "킥서브 입문 가이드", description: "안정감과 바운드 변화를 함께 노릴 수 있는 킥서브의 기본 원리를 정리합니다.", category: "Serve" },
  { slug: "tennis-slice-serve-guide", title: "슬라이스 서브 가이드", description: "코스와 리턴 강도를 흔드는 슬라이스 서브 사용법을 실전 중심으로 설명합니다.", category: "Serve" },
  { slug: "tennis-forehand-depth-control-guide", title: "포핸드 깊이 조절 가이드", description: "포핸드를 깊고 안정적으로 보내기 위한 타점, 높이, 목표 설정법을 정리합니다.", category: "Forehand" },
  { slug: "tennis-backhand-return-guide", title: "백핸드 리턴 가이드", description: "강한 서브를 백핸드로 안정적으로 받아내는 준비 자세와 리턴 패턴을 소개합니다.", category: "Backhand" },
  { slug: "tennis-match-video-review-guide", title: "경기 영상 복기 가이드", description: "경기 영상을 단순 시청이 아니라 개선 도구로 활용하는 복기 구조를 설명합니다.", category: "Analysis" },
  { slug: "tennis-tournament-preparation-checklist", title: "대회 준비 체크리스트", description: "대회 전 준비물, 일정, 루틴, 컨디션 관리 항목을 한 번에 정리합니다.", category: "Competition" },
];

const PLAYER_BATCH = [
  ["lorenzo-sonego", "Lorenzo Sonego", "male", "Italy"],
  ["marcos-giron", "Marcos Giron", "male", "USA"],
  ["alejandro-tabilo", "Alejandro Tabilo", "male", "Chile"],
  ["tomas-martin-etcheverry", "Tomas Martin Etcheverry", "male", "Argentina"],
  ["pedro-martinez", "Pedro Martinez", "male", "Spain"],
  ["sebastian-ofner", "Sebastian Ofner", "male", "Austria"],
  ["alexandre-muller", "Alexandre Muller", "male", "France"],
  ["francisco-comesana", "Francisco Comesana", "male", "Argentina"],
  ["camilo-ugo-carabelli", "Camilo Ugo Carabelli", "male", "Argentina"],
  ["zizou-bergs", "Zizou Bergs", "male", "Belgium"],
  ["hamad-medjedovic", "Hamad Medjedovic", "male", "Serbia"],
  ["jacob-fearnley", "Jacob Fearnley", "male", "Great Britain"],
  ["billy-harris", "Billy Harris", "male", "Great Britain"],
  ["thiago-seyboth-wild", "Thiago Seyboth Wild", "male", "Brazil"],
  ["joao-lucas-reis-da-silva", "Joao Lucas Reis da Silva", "male", "Brazil"],
  ["nishesh-basavareddy", "Nishesh Basavareddy", "male", "USA"],
  ["clara-tauson", "Clara Tauson", "female", "Denmark"],
  ["lulu-sun", "Lulu Sun", "female", "New Zealand"],
  ["mccartney-kessler", "McCartney Kessler", "female", "USA"],
  ["ashlyn-krueger", "Ashlyn Krueger", "female", "USA"],
  ["peyton-stearns", "Peyton Stearns", "female", "USA"],
  ["alycia-parks", "Alycia Parks", "female", "USA"],
  ["sonay-kartal", "Sonay Kartal", "female", "Great Britain"],
  ["olga-danilovic", "Olga Danilovic", "female", "Serbia"],
  ["yulia-putintseva", "Yulia Putintseva", "female", "Kazakhstan"],
  ["rebeka-masarova", "Rebeka Masarova", "female", "Spain"],
  ["elena-avanesyan", "Elena Avanesyan", "female", "Armenia"],
  ["moyuka-uchijima", "Moyuka Uchijima", "female", "Japan"],
  ["eva-lys", "Eva Lys", "female", "Germany"],
  ["robin-montgomery", "Robin Montgomery", "female", "USA"],
];

const UTILITY_BATCH = [
  ["doubles-positioning-simulator", "복식 포지셔닝 시뮬레이터", "Doubles"],
  ["shot-selection-trainer", "샷 선택 트레이너", "Strategy"],
  ["tiebreak-pressure-simulator", "타이브레이크 압박 시뮬레이터", "Mental"],
  ["serve-placement-mapper", "서브 코스 매퍼", "Serve"],
  ["return-position-calculator", "리턴 위치 계산기", "Return"],
  ["matchday-packing-checklist", "경기일 준비물 체크리스트", "Planning"],
  ["hydration-planner", "수분 섭취 플래너", "Recovery"],
  ["sleep-readiness-check", "수면 준비도 체크", "Recovery"],
  ["recovery-routine-generator", "회복 루틴 생성기", "Recovery"],
  ["warmup-routine-builder", "워밍업 루틴 빌더", "Training"],
  ["cooldown-routine-builder", "쿨다운 루틴 빌더", "Recovery"],
  ["practice-drill-generator", "연습 드릴 생성기", "Training"],
  ["practice-wall-drill-planner", "벽치기 드릴 플래너", "Training"],
  ["tournament-budget-calculator", "대회 예산 계산기", "Planning"],
  ["court-surface-advisor", "코트 표면 추천기", "Strategy"],
  ["rally-consistency-tracker", "랠리 일관성 트래커", "Training"],
  ["unforced-error-audit", "범실 분석기", "Analysis"],
  ["match-video-review-template", "경기 영상 리뷰 템플릿", "Analysis"],
  ["tennis-goal-streak-tracker", "테니스 목표 연속 달성 트래커", "Training"],
  ["equipment-maintenance-scheduler", "장비 관리 스케줄러", "Planning"],
  ["grip-size-checker", "그립 사이즈 체커", "Equipment"],
  ["overgrip-replacement-reminder", "오버그립 교체 알림", "Equipment"],
  ["string-replacement-reminder", "스트링 교체 알림", "Equipment"],
  ["shoe-wear-tracker", "신발 마모 추적기", "Equipment"],
  ["doubles-chemistry-test", "복식 궁합 테스트", "Doubles"],
  ["partner-compatibility-check", "파트너 적합도 체크", "Doubles"],
  ["junior-development-roadmap", "주니어 성장 로드맵", "Training"],
  ["adult-beginner-roadmap", "성인 입문 로드맵", "Beginner"],
  ["tennis-time-availability-planner", "테니스 시간 관리 플래너", "Planning"],
  ["travel-pack-planner", "원정 짐싸기 플래너", "Planning"],
];

module.exports = { BLOG_BATCH, PLAYER_BATCH, UTILITY_BATCH };
